title: Blog de Gentil Kiwi
description: L'aide mémoire d'un Kiwi
permalink: none

# theme: minima - obsolete version on GitHub Pages :(
plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  skin: dark
  hide_site_feed_link: true
  social_links:
    - title: gentilkiwi's GitHub
      icon: github
      url: https://github.com/gentilkiwi
    - title: gentilkiwi's X (formerly Twitter)
      icon: x-twitter
      url: https://x.com/gentilkiwi
    - title: gentilkiwi's LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/delpy